#Compare Searchengines and Consensus (HeLA HCD)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/075-TextExporter-out/OT_HeLA_FTdig_2010July29-05hcd.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/073-TextExporter-out/OT_HeLA_FTdig_2010July29-05hcd.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/079-TextExporter-out/OT_HeLA_FTdig_2010July29-05hcd.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/077-TextExporter-out/OT_HeLA_FTdig_2010July29-05hcd.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/090-TextExporter-out/OT_HeLA_FTdig_2010July29-05hcd.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_HeLA_FTdig_2010July29-05hcd.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_HeLA_HCD/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_HeLA_FTdig_2010July29-05hcd.unknown","purple")
	)
searchresultplot("Comparison of search engines, DB: GenCode", 0.05, searchengines, 15212, "P:/Petra/TOPPAS/Results/HELA/HCD/ROC_HeLAHCD_v2.png")

#Compare Searchengines and Consensus (HeLA CID)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/075-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/073-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/079-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/077-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/090-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_Hela_2011Nov17-120cid.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_Hela_2011Nov17-120cid.unknown","purple")
	)
searchresultplot("Comparison of search engines, DB: GenCode", 0.05, searchengines, 27538, "P:/Petra/TOPPAS/Results/HELA/ROC_HeLACID.png")

#Compare Searchengines and Consensus (HeLA CID PepIons)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/075-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/073-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/079-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/077-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/090-TextExporter-out/OT_Hela_2011Nov17-120cid.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_Hela_2011Nov17-120cid.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngine_v5_HeLA_CID_PepIons/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_Hela_2011Nov17-120cid.unknown","purple")
	)
searchresultplot("Comparison of search engines (HeLA CID)", 0.05, searchengines, 27538, "P:/Petra/TOPPAS/Results/HELA/ROC_HeLACID_PepIons.png")

#Compare Searchengines and Consensus (Ecoli CID)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/075-TextExporter-out/ecoli_cid_input.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/073-TextExporter-out/ecoli_cid_input.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/079-TextExporter-out/ecoli_cid_input.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/077-TextExporter-out/ecoli_cid_input.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/090-TextExporter-out/ecoli_cid_input.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/043-GenericWrapper-EToolout_psms/ecoli_cid_input.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID/TOPPAS_out/006-GenericWrapper-EToolout_tab/ecoli_cid_input.unknown","purple")
	)
searchresultplot("Comparison of search engines (E.coli CID)", 0.05, searchengines, 31874, "P:/Petra/TOPPAS/Results/Ecoli_CID/ROC_EcoliCID.png")

#Compare Searchengines and Consensus (Ecoli CID PepIons)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/075-TextExporter-out/ecoli_cid_input.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/073-TextExporter-out/ecoli_cid_input.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/079-TextExporter-out/ecoli_cid_input.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/077-TextExporter-out/ecoli_cid_input.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/090-TextExporter-out/ecoli_cid_input.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/043-GenericWrapper-EToolout_psms/ecoli_cid_input.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_CID_PepIons/TOPPAS_out/006-GenericWrapper-EToolout_tab/ecoli_cid_input.unknown","purple")
	)
searchresultplot("Comparison of search engines (E.coli CID)", 0.05, searchengines, 31874, "P:/Petra/TOPPAS/Results/Ecoli_CID/ROC_EcoliCID_PepIons.png")

#Compare Searchengines and Consensus (Ecoli E3 CID)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/075-TextExporter-out/ecoli_e3_cid_input.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/073-TextExporter-out/ecoli_e3_cid_input.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/079-TextExporter-out/ecoli_e3_cid_input.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/077-TextExporter-out/ecoli_e3_cid_input.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/090-TextExporter-out/ecoli_e3_cid_input.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/043-GenericWrapper-EToolout_psms/ecoli_e3_cid_input.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_CID/TOPPAS_out/006-GenericWrapper-EToolout_tab/ecoli_e3_cid_input.unknown","purple")
	)
searchresultplot("Comparison of search engines (E.coli E3 CID)", 0.05, searchengines, 62753, "P:/Petra/TOPPAS/Results/Ecoli_E3_CID/ROC_EcoliE3CID.png")

#Compare Searchengines and Consensus (Ecoli ETD)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/061-TextExporter-out/ecoli_etd_input.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/059-TextExporter-out/ecoli_etd_input.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/065-TextExporter-out/ecoli_etd_input.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/063-TextExporter-out/ecoli_etd_input.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/076-TextExporter-out/ecoli_etd_input.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/039-GenericWrapper-EToolout_psms/ecoli_etd_input.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_ETD/TOPPAS_out/006-GenericWrapper-EToolout_tab/ecoli_etd_input.unknown","purple")
	)
searchresultplot("Comparison of search engines (E.coli ETD)", 0.05, searchengines, 20386, "P:/Petra/TOPPAS/Results/Ecoli_ETD/ROC_EcoliETD.png")

#Compare Searchengines and Consensus (Ecoli E3 ETD)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/061-TextExporter-out/ecoli_e3_etd_input.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/059-TextExporter-out/ecoli_e3_etd_input.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/065-TextExporter-out/ecoli_e3_etd_input.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/063-TextExporter-out/ecoli_e3_etd_input.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/076-TextExporter-out/ecoli_e3_etd_input.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/039-GenericWrapper-EToolout_psms/ecoli_e3_etd_input.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_Ecoli_E3_ETD/TOPPAS_out/006-GenericWrapper-EToolout_tab/ecoli_e3_etd_input.unknown","purple")
	)
searchresultplot("Comparison of search engines (E.coli E3 ETD)", 0.05, searchengines, 35144, "P:/Petra/TOPPAS/Results/Ecoli_E3_ETD/ROC_EcoliE3ETD.png")

#Compare Searchengines and Consensus (UPS1 CID)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/075-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/073-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/079-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/077-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/091-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-CID_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-CID_1.unknown","purple")
	)
searchresultplot("Comparison of search engines (UPS1 CID)", 0.05, searchengines, 15454, "P:/Petra/TOPPAS/Results/UPS1/CID/ROC_UPS1CID.png")

#Compare Searchengines and Consensus (UPS1 CID BiDB)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/075-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/073-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/079-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/077-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/091-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-CID_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-CID_1.unknown","purple")
	)
searchresultplot("Comparison of search engines, DB: Human Bipartite", 0.05, searchengines, 15454, "P:/Petra/TOPPAS/Results/UPS1/CID_BiDB/ROC_UPS1CID_BiDB.png")

#Compare Searchengines and Consensus (UPS1 CID BiDB PepIons)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/075-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/073-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/079-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/077-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/091-TextExporter-out/OT_UPS1_10fm_2009Oct21-CID_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/043-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-CID_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_CID_UPS1_BiDB_PepIons/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-CID_1.unknown","purple")
	)
searchresultplot("Comparison of search engines (UPS1 CID BiDB)", 0.05, searchengines, 15454, "P:/Petra/TOPPAS/Results/UPS1/CID_BiDB/ROC_UPS1CID_BiDB_PepIons.png")

#Compare Searchengines and Consensus (UPS1 ETD)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/061-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/059-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/065-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/063-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/076-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/039-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","purple")
	)
searchresultplot("Comparison of search engines (UPS1 ETD)", 0.05, searchengines, 11235, "P:/Petra/TOPPAS/Results/UPS1/ETD/ROC_UPS1ETD.png")

#Compare Searchengines and Consensus (UPS1 ETD BiDB)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/061-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/059-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/065-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/063-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/076-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/039-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_Tol/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","purple")
	)
searchresultplot("Comparison of search engines, DB: Human Bipartite", 0.05, searchengines, 11235, "P:/Petra/TOPPAS/Results/UPS1/ETD_BiDB/ROC_UPS1ETD_BiDB_Tol.png")

#Compare Searchengines and Consensus (UPS1 ETD BiDB)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/061-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/059-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/065-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/063-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/076-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/039-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","purple")
	)
searchresultplot("Comparison of search engines, DB: Human Bipartite", 0.05, searchengines, 11235, "P:/Petra/TOPPAS/Results/UPS1/ETD_BiDB/ROC_UPS1ETD_BiDB.png")

#Compare Searchengines and Consensus (UPS1 ETD BiDB PepIons)
searchengines = list(Mascot = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/061-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","red")
	, MSGFPlus = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/059-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","black")
	, OMSSA = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/065-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","green")
	, XTandem = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/063-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","blue")
	, ConsensusID = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/076-TextExporter-out/OT_UPS1_10fm_2009Oct21-ETD_1.csv","pink")
	, MSGFPlusPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/039-GenericWrapper-EToolout_psms/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","orange")
	, MascotPercolator = c("P:/Petra/TOPPAS/TOPPAS_OUT/CompareSearchEngines_v5_ETD_UPS1_BiDB_PepIons/TOPPAS_out/006-GenericWrapper-EToolout_tab/OT_UPS1_10fm_2009Oct21-ETD_1.unknown","purple")
	)
searchresultplot("Comparison of search engines (UPS1 ETD BiDB)", 0.05, searchengines, 11235, "P:/Petra/TOPPAS/Results/UPS1/ETD_BiDB/ROC_UPS1ETD_BiDB_PepIons.png")